#!/bin/bash
prim_set=true
have_exe_page=false
have_page=false
page_path="$(pwd)/phx/components/Print3/zxps/IPS/SPISim/page"
csr_path="$(pwd)/phx/components/Print3/zxps/IPS/DOResources/csr_resources"
echo "Setup simulator environment"
echo "Print FW version:<Print3>"
#check if we are in correct path and project has been compiled.
if [ ! -d "$(pwd)/phx" ];then
	echo "Error! Could not found your scm directory."
	echo "usage:run 'Jsim <test fiel>' in you scm directory."
	exit
fi
#check if we have given a valid source file
if [ ! -f "$1" ];then
	echo "Error! Please provide a valid source file."
	echo "usage:run 'Jsim <test fiel>' in you scm directory."
	exit
fi
#prepare Jsim directory
if [ ! -d "$(pwd)/Jsim" ];then
	mkdir $(pwd)/Jsim
	echo "mkdir $(pwd)/Jsim"
else
	rm -rf $(pwd)/Jsim/*
	echo "remove $(pwd)/Jsim"
fi
#check if we have had page and csr 
if [ ! -f "$page_path" ] || [ ! -d "$csr_path" ];then
	echo "ERROR:Please change directory to $(pwd)/phx and run 'phxmake -j12 Product=<your product> TargPair=<target compiler> Flavor=debug Simulator=true' first."
	exit
fi
#move page and csr to Jsim
cp -r $page_path $(pwd)/Jsim/.
cp -r $csr_path $(pwd)/Jsim/.
echo "move page and csr to Jsim"
mkdir $(pwd)/Jsim/PSdisk0
echo "mkdir PSdisk0"
ln -s $(pwd)/Jsim/csr_resources $(pwd)/Jsim/PSdisk0/csr_resources
cd $(pwd)/Jsim/
#generate simulator output and preview 
page -Ot<$1
gimp page*.tif
